Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Public\\StoreProducts\\Perishable",
            "name": "Perishable",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Perishable.html"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Perishable\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Perishable\u0020constructor.",
            "url": "classes/App-Public-StoreProducts-Perishable.html#method___construct"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Perishable\u003A\u003AgetSalePrice\u0028\u0029",
            "name": "getSalePrice",
            "summary": "Return\u0020sale\u0020price.",
            "url": "classes/App-Public-StoreProducts-Perishable.html#method_getSalePrice"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Perishable\u003A\u003AgetDiscount\u0028\u0029",
            "name": "getDiscount",
            "summary": "Return\u0020discount.",
            "url": "classes/App-Public-StoreProducts-Perishable.html#method_getDiscount"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Perishable\u003A\u003AgetBasePrice\u0028\u0029",
            "name": "getBasePrice",
            "summary": "Return\u0020base\u0020price\u0020with\u0020discount.",
            "url": "classes/App-Public-StoreProducts-Perishable.html#method_getBasePrice"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Perishable\u003A\u003AsetExpirationDate\u0028\u0029",
            "name": "setExpirationDate",
            "summary": "Set\u0020the\u0020expiration\u0020Date.",
            "url": "classes/App-Public-StoreProducts-Perishable.html#method_setExpirationDate"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Perishable\u003A\u003AgetdaysToExpire\u0028\u0029",
            "name": "getdaysToExpire",
            "summary": "Returns\u0020number\u0020of\u0020days\u0020to\u0020Expire.",
            "url": "classes/App-Public-StoreProducts-Perishable.html#method_getdaysToExpire"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Perishable\u003A\u003AisExpired\u0028\u0029",
            "name": "isExpired",
            "summary": "Check\u0020if\u0020product\u0020is\u0020expired",
            "url": "classes/App-Public-StoreProducts-Perishable.html#method_isExpired"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Perishable\u003A\u003AdateDiff\u0028\u0029",
            "name": "dateDiff",
            "summary": "Return\u0020the\u0020difference\u0020between\u0020current\u0020date\u0020and\u0020expiration\u0020date.",
            "url": "classes/App-Public-StoreProducts-Perishable.html#method_dateDiff"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Perishable\u003A\u003AgetCurrDate\u0028\u0029",
            "name": "getCurrDate",
            "summary": "Return\u0020the\u0020current\u0020date.",
            "url": "classes/App-Public-StoreProducts-Perishable.html#method_getCurrDate"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Perishable\u003A\u003AgetExpirationDate\u0028\u0029",
            "name": "getExpirationDate",
            "summary": "Return\u0020expiration\u0020date.",
            "url": "classes/App-Public-StoreProducts-Perishable.html#method_getExpirationDate"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Perishable\u003A\u003A\u0024expirationDate",
            "name": "expirationDate",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Perishable.html#property_expirationDate"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Perishable\u003A\u003A\u0024firstDiscount",
            "name": "firstDiscount",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Perishable.html#property_firstDiscount"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Perishable\u003A\u003A\u0024secondDiscount",
            "name": "secondDiscount",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Perishable.html#property_secondDiscount"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Product",
            "name": "Product",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Product.html"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Product\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Product\u0020constructor.",
            "url": "classes/App-Public-StoreProducts-Product.html#method___construct"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Product\u003A\u003AgetSalePrice\u0028\u0029",
            "name": "getSalePrice",
            "summary": "Return\u0020the\u0020sale\u0020price.",
            "url": "classes/App-Public-StoreProducts-Product.html#method_getSalePrice"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Product\u003A\u003AgetShippingCost\u0028\u0029",
            "name": "getShippingCost",
            "summary": "Return\u0020the\u0020shipping\u0020cost.",
            "url": "classes/App-Public-StoreProducts-Product.html#method_getShippingCost"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Product\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "Get\u0020product\u0020name.",
            "url": "classes/App-Public-StoreProducts-Product.html#method_getName"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Product\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "Set\u0020product\u0020name.",
            "url": "classes/App-Public-StoreProducts-Product.html#method_setName"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Product\u003A\u003AgetBasePrice\u0028\u0029",
            "name": "getBasePrice",
            "summary": "Return\u0020product\u0020base\u0020price.",
            "url": "classes/App-Public-StoreProducts-Product.html#method_getBasePrice"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Product\u003A\u003AsetBasePrice\u0028\u0029",
            "name": "setBasePrice",
            "summary": "Set\u0020product\u0020base\u0020price.",
            "url": "classes/App-Public-StoreProducts-Product.html#method_setBasePrice"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Product\u003A\u003AgetManufacturer\u0028\u0029",
            "name": "getManufacturer",
            "summary": "Return\u0020the\u0020manufacturer.",
            "url": "classes/App-Public-StoreProducts-Product.html#method_getManufacturer"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Product\u003A\u003AsetManufacturer\u0028\u0029",
            "name": "setManufacturer",
            "summary": "Set\u0020product\u0020manufacturer.",
            "url": "classes/App-Public-StoreProducts-Product.html#method_setManufacturer"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Product\u003A\u003AgetWeight\u0028\u0029",
            "name": "getWeight",
            "summary": "Return\u0020product\u0020weight.",
            "url": "classes/App-Public-StoreProducts-Product.html#method_getWeight"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Product\u003A\u003AsetWeight\u0028\u0029",
            "name": "setWeight",
            "summary": "Set\u0020weight.",
            "url": "classes/App-Public-StoreProducts-Product.html#method_setWeight"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Product\u003A\u003AgetVolume\u0028\u0029",
            "name": "getVolume",
            "summary": "Return\u0020the\u0020volume.",
            "url": "classes/App-Public-StoreProducts-Product.html#method_getVolume"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Product\u003A\u003AsetVolume\u0028\u0029",
            "name": "setVolume",
            "summary": "Set\u0020product\u0020volume.",
            "url": "classes/App-Public-StoreProducts-Product.html#method_setVolume"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Product\u003A\u003AgetTax\u0028\u0029",
            "name": "getTax",
            "summary": "Get\u0020the\u0020product\u0020tax.",
            "url": "classes/App-Public-StoreProducts-Product.html#method_getTax"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Product\u003A\u003AsetTax\u0028\u0029",
            "name": "setTax",
            "summary": "Set\u0020product\u0020tax.",
            "url": "classes/App-Public-StoreProducts-Product.html#method_setTax"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Product\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Product.html#property_name"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Product\u003A\u003A\u0024basePrice",
            "name": "basePrice",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Product.html#property_basePrice"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Product\u003A\u003A\u0024manufacturer",
            "name": "manufacturer",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Product.html#property_manufacturer"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Product\u003A\u003A\u0024weight",
            "name": "weight",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Product.html#property_weight"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Product\u003A\u003A\u0024volume",
            "name": "volume",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Product.html#property_volume"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Product\u003A\u003A\u0024tax",
            "name": "tax",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Product.html#property_tax"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\Event",
            "name": "Event",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Services-Event.html"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\Event\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Event\u0020Constructor.",
            "url": "classes/App-Public-StoreProducts-Services-Event.html#method___construct"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\Event\u003A\u003AgetSalePrice\u0028\u0029",
            "name": "getSalePrice",
            "summary": "Return\u0020sale\u0020price.",
            "url": "classes/App-Public-StoreProducts-Services-Event.html#method_getSalePrice"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\Event\u003A\u003AgetIncrement\u0028\u0029",
            "name": "getIncrement",
            "summary": "Return\u0020discount.",
            "url": "classes/App-Public-StoreProducts-Services-Event.html#method_getIncrement"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\Event\u003A\u003AgetdaysToExpire\u0028\u0029",
            "name": "getdaysToExpire",
            "summary": "Returns\u0020number\u0020of\u0020days\u0020to\u0020Expire.",
            "url": "classes/App-Public-StoreProducts-Services-Event.html#method_getdaysToExpire"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\Event\u003A\u003AgetBasePrice\u0028\u0029",
            "name": "getBasePrice",
            "summary": "Return\u0020base\u0020price\u0020with\u0020discount.",
            "url": "classes/App-Public-StoreProducts-Services-Event.html#method_getBasePrice"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\Event\u003A\u003AsetBasePrice\u0028\u0029",
            "name": "setBasePrice",
            "summary": "Set\u0020the\u0020value\u0020of\u0020basePrice",
            "url": "classes/App-Public-StoreProducts-Services-Event.html#method_setBasePrice"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\Event\u003A\u003AsetExpirationDate\u0028\u0029",
            "name": "setExpirationDate",
            "summary": "Set\u0020the\u0020expiration\u0020Date.",
            "url": "classes/App-Public-StoreProducts-Services-Event.html#method_setExpirationDate"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\Event\u003A\u003AgetDaysLeft\u0028\u0029",
            "name": "getDaysLeft",
            "summary": "Returns\u0020number\u0020of\u0020days\u0020left.",
            "url": "classes/App-Public-StoreProducts-Services-Event.html#method_getDaysLeft"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\Event\u003A\u003AisEventCompleted\u0028\u0029",
            "name": "isEventCompleted",
            "summary": "Return\u0020if\u0020event\u0020has\u0020happened.",
            "url": "classes/App-Public-StoreProducts-Services-Event.html#method_isEventCompleted"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\Event\u003A\u003AdateDiff\u0028\u0029",
            "name": "dateDiff",
            "summary": "Return\u0020the\u0020difference\u0020between\u0020current\u0020date\u0020and\u0020event\u0020date.",
            "url": "classes/App-Public-StoreProducts-Services-Event.html#method_dateDiff"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\Event\u003A\u003AgetCurrDate\u0028\u0029",
            "name": "getCurrDate",
            "summary": "Return\u0020the\u0020current\u0020date.",
            "url": "classes/App-Public-StoreProducts-Services-Event.html#method_getCurrDate"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\Event\u003A\u003AgetEventDate\u0028\u0029",
            "name": "getEventDate",
            "summary": "Return\u0020event\u0020date.",
            "url": "classes/App-Public-StoreProducts-Services-Event.html#method_getEventDate"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\Event\u003A\u003A\u0024eventDate",
            "name": "eventDate",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Services-Event.html#property_eventDate"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\Event\u003A\u003A\u0024firstDiscount",
            "name": "firstDiscount",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Services-Event.html#property_firstDiscount"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\Event\u003A\u003A\u0024secondDiscount",
            "name": "secondDiscount",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Services-Event.html#property_secondDiscount"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\Event\u003A\u003A\u0024basePrice",
            "name": "basePrice",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Services-Event.html#property_basePrice"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\Event\u003A\u003A\u0024tax",
            "name": "tax",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Services-Event.html#property_tax"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\MixedService",
            "name": "MixedService",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Services-MixedService.html"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\MixedService\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Mixed\u0020service\u0020constructor.",
            "url": "classes/App-Public-StoreProducts-Services-MixedService.html#method___construct"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\MixedService\u003A\u003AsetExpirationDate\u0028\u0029",
            "name": "setExpirationDate",
            "summary": "Set\u0020the\u0020expiration\u0020Date.",
            "url": "classes/App-Public-StoreProducts-Services-MixedService.html#method_setExpirationDate"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\MixedService\u003A\u003AaddSession\u0028\u0029",
            "name": "addSession",
            "summary": "Add\u00201\u0020Session",
            "url": "classes/App-Public-StoreProducts-Services-MixedService.html#method_addSession"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\MixedService\u003A\u003AdeleteSession\u0028\u0029",
            "name": "deleteSession",
            "summary": "Remove\u00201\u0020Session",
            "url": "classes/App-Public-StoreProducts-Services-MixedService.html#method_deleteSession"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\MixedService\u003A\u003AgetnSession\u0028\u0029",
            "name": "getnSession",
            "summary": "Return\u0020number\u0020of\u0020sessions.",
            "url": "classes/App-Public-StoreProducts-Services-MixedService.html#method_getnSession"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\MixedService\u003A\u003AsetnSession\u0028\u0029",
            "name": "setnSession",
            "summary": "Set\u0020number\u0020of\u0020sessions.",
            "url": "classes/App-Public-StoreProducts-Services-MixedService.html#method_setnSession"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\MixedService\u003A\u003AgetDaysLeft\u0028\u0029",
            "name": "getDaysLeft",
            "summary": "Returns\u0020number\u0020of\u0020days\u0020left.",
            "url": "classes/App-Public-StoreProducts-Services-MixedService.html#method_getDaysLeft"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\MixedService\u003A\u003AisMixedCompleted\u0028\u0029",
            "name": "isMixedCompleted",
            "summary": "Check\u0020if\u0020event\u0020has\u0020happened",
            "url": "classes/App-Public-StoreProducts-Services-MixedService.html#method_isMixedCompleted"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\MixedService\u003A\u003AgetCurrDate\u0028\u0029",
            "name": "getCurrDate",
            "summary": "Return\u0020the\u0020current\u0020date.",
            "url": "classes/App-Public-StoreProducts-Services-MixedService.html#method_getCurrDate"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\MixedService\u003A\u003AdateDiff\u0028\u0029",
            "name": "dateDiff",
            "summary": "Return\u0020the\u0020difference\u0020between\u0020current\u0020date\u0020and\u0020event\u0020date.",
            "url": "classes/App-Public-StoreProducts-Services-MixedService.html#method_dateDiff"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\MixedService\u003A\u003AgetEventDate\u0028\u0029",
            "name": "getEventDate",
            "summary": "Return\u0020mixed\u0020date.",
            "url": "classes/App-Public-StoreProducts-Services-MixedService.html#method_getEventDate"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\MixedService\u003A\u003A\u0024nSessions",
            "name": "nSessions",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Services-MixedService.html#property_nSessions"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\MixedService\u003A\u003A\u0024eventDate",
            "name": "eventDate",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Services-MixedService.html#property_eventDate"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\NormalService",
            "name": "NormalService",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Services-NormalService.html"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\NormalService\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Normal\u0020service\u0020constructor.",
            "url": "classes/App-Public-StoreProducts-Services-NormalService.html#method___construct"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\NormalService\u003A\u003AgetSalePrice\u0028\u0029",
            "name": "getSalePrice",
            "summary": "Return\u0020the\u0020sale\u0020price.",
            "url": "classes/App-Public-StoreProducts-Services-NormalService.html#method_getSalePrice"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\NormalService\u003A\u003AgetBasePrice\u0028\u0029",
            "name": "getBasePrice",
            "summary": "Return\u0020service\u0020base\u0020price.",
            "url": "classes/App-Public-StoreProducts-Services-NormalService.html#method_getBasePrice"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\NormalService\u003A\u003AsetBasePrice\u0028\u0029",
            "name": "setBasePrice",
            "summary": "Set\u0020service\u0020base\u0020price.",
            "url": "classes/App-Public-StoreProducts-Services-NormalService.html#method_setBasePrice"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\NormalService\u003A\u003AgetManufacturer\u0028\u0029",
            "name": "getManufacturer",
            "summary": "Return\u0020the\u0020service\u0020manufacturer.",
            "url": "classes/App-Public-StoreProducts-Services-NormalService.html#method_getManufacturer"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\NormalService\u003A\u003AsetManufacturer\u0028\u0029",
            "name": "setManufacturer",
            "summary": "Set\u0020service\u0020manufacturer.",
            "url": "classes/App-Public-StoreProducts-Services-NormalService.html#method_setManufacturer"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\NormalService\u003A\u003AgetTax\u0028\u0029",
            "name": "getTax",
            "summary": "Get\u0020the\u0020servivce\u0020tax.",
            "url": "classes/App-Public-StoreProducts-Services-NormalService.html#method_getTax"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\NormalService\u003A\u003AsetTax\u0028\u0029",
            "name": "setTax",
            "summary": "Set\u0020servivce\u0020tax.",
            "url": "classes/App-Public-StoreProducts-Services-NormalService.html#method_setTax"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\NormalService\u003A\u003A\u0024basePrice",
            "name": "basePrice",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Services-NormalService.html#property_basePrice"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\NormalService\u003A\u003A\u0024manufacturer",
            "name": "manufacturer",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Services-NormalService.html#property_manufacturer"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\NormalService\u003A\u003A\u0024tax",
            "name": "tax",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Services-NormalService.html#property_tax"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\Service",
            "name": "Service",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Services-Service.html"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\Service\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Service\u0020constructor.",
            "url": "classes/App-Public-StoreProducts-Services-Service.html#method___construct"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\Service\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "Return\u0020name.",
            "url": "classes/App-Public-StoreProducts-Services-Service.html#method_getName"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\Service\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "Set\u0020name.",
            "url": "classes/App-Public-StoreProducts-Services-Service.html#method_setName"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\Service\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Services-Service.html#property_name"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\SessionService",
            "name": "SessionService",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Services-SessionService.html"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\SessionService\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Session\u0020service\u0020constructor.",
            "url": "classes/App-Public-StoreProducts-Services-SessionService.html#method___construct"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\SessionService\u003A\u003AaddSession\u0028\u0029",
            "name": "addSession",
            "summary": "Add\u00201\u0020Session.",
            "url": "classes/App-Public-StoreProducts-Services-SessionService.html#method_addSession"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\SessionService\u003A\u003AdeleteSession\u0028\u0029",
            "name": "deleteSession",
            "summary": "Delete\u00201\u0020Session.",
            "url": "classes/App-Public-StoreProducts-Services-SessionService.html#method_deleteSession"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\SessionService\u003A\u003AgetnSession\u0028\u0029",
            "name": "getnSession",
            "summary": "Return\u0020number\u0020of\u0020sessions.",
            "url": "classes/App-Public-StoreProducts-Services-SessionService.html#method_getnSession"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\SessionService\u003A\u003AsetnSession\u0028\u0029",
            "name": "setnSession",
            "summary": "Set\u0020number\u0020of\u0020sessions.",
            "url": "classes/App-Public-StoreProducts-Services-SessionService.html#method_setnSession"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services\\SessionService\u003A\u003A\u0024nSessions",
            "name": "nSessions",
            "summary": "",
            "url": "classes/App-Public-StoreProducts-Services-SessionService.html#property_nSessions"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Public",
            "name": "Public",
            "summary": "",
            "url": "namespaces/app-public.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Public\\Partials",
            "name": "Partials",
            "summary": "",
            "url": "namespaces/app-public-partials.html"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts",
            "name": "StoreProducts",
            "summary": "",
            "url": "namespaces/app-public-storeproducts.html"
        },                {
            "fqsen": "\\App\\Public\\StoreProducts\\Services",
            "name": "Services",
            "summary": "",
            "url": "namespaces/app-public-storeproducts-services.html"
        }            ]
);
